export { canonicalStoreDigest, closeIntentDigest, OperationConflict, OperationInDoubt, ReceiptRejected, RevisionConflict, TrajectaStore } from "./store.ts";
export { LockInDoubt, LockTimeout, NestedRootLock, withRootWriteLock } from "./lock.ts";
export type { StoreFaultPoint } from "./store.ts";
export { TrajectaRelay } from "./relay.ts";
export type * from "./types.ts";
export type { HandoffInput, TransportReceipt } from "./relay.ts";
export { assertResumeAttempt, assertTransferPacket, digestResumeAttempt, stableSerialize } from "./adapters/proof/attempt-contract.ts";
export type { ResumeAttemptCode, ResumeAttemptInputV1, ResumeAttemptReceiptV1, ResumeTargetV1 } from "./adapters/proof/attempt-contract.ts";
export { ResumeAttemptLedger } from "./adapters/proof/attempt-ledger.ts";
export { attemptVerifiedResume, inspectVerifiedResume } from "./adapters/proof/attempt-resume.ts";
export { renderResumeReceipt } from "./adapters/proof/receipt-renderer.ts";
export { LearningLayer, GUARDS, GUARD_IDS, CHRONICLE_STAGES } from "./learning.ts";
export type { CheckActionInput, GuardId, Incident, Invariant, Milestone, Friction, Tier } from "./learning.ts";
export { ApprovalRejected, assertOwnerApproval, invariantDigest, issueReceipt, newReceiptId, receiptJournal, receiptResolver } from "./receipts.ts";
export type { OwnerApprovalReceipt, Receipt } from "./receipts.ts";
